#!/usr/bin/perl -w

use ExtUtils::Packlist;
use ExtUtils::Installed;

$ARGV[0] or die "Usage: $0 Module::Name\n";

my $mod = $ARGV[0];
my $inst = ExtUtils::Installed->new();

foreach my $item (sort($inst->files($mod))) {
	print "module file: $item\n";
}

my $packfile = $inst->packlist($mod)->packlist_file();
print "packlist file: $packfile\n";
